services:
  web:
    restart: unless-stopped
    build:
      context: ./service/httpd
    volumes:
      - ${WWW_ROOT:-../src}:/home/www
      - ${CONF_ROOT:-./conf}/httpd:/usr/local/apache2/conf
    ports:
      - 80:80
      - 443:443
    networks:
      default:
        ipv4_address: 172.0.0.2

  db:
    restart: unless-stopped
    image: mysql:8.3
    platform: linux/arm64
    volumes:
      - ../mysql:/var/lib/mysql
      - ${CONF_ROOT:-./conf}/mysql:/etc/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-elql}
    networks:
      default:
        ipv4_address: 172.0.0.3

  db5:
    restart: unless-stopped
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - ../mysql5:/var/lib/mysql
      - ${CONF_ROOT:-./conf}/mysql5:/etc/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-elql}
    networks:
      default:
        ipv4_address: 172.0.0.5
        aliases:
          - whoisgh_db
          - dev.whoiswork.com
          - raindev

  dns:
    restart: unless-stopped
    build:
      context: ./service/dnsmasq
    volumes:
      - ${CONF_ROOT:-./conf}/dnsmasq.d:/etc/dnsmasq.d
    ports:
      - 53:53/tcp
      - 53:53/udp
    networks:
      default:
        ipv4_address: 172.0.0.254
    cap_add:
      - NET_ADMIN

  php83:
    restart: unless-stopped
    build:
      context: ./service/php83-fpm
    volumes:
      - ${WWW_ROOT:-../src}:/home/www
      - ${CONF_ROOT:-./conf}/php/8.3:/usr/local/etc/php
      - /opt/work/php:/opt/work/php
    networks:
      default:
        ipv4_address: 172.0.0.83

  php82:
    restart: unless-stopped
    build:
      context: ./service/php82-fpm
    volumes:
      - ${WWW_ROOT:-../src}:/home/www
      - ${CONF_ROOT:-./conf}/php/8.2:/usr/local/etc/php
      - /opt/work/php:/opt/work/php
    networks:
      default:
        ipv4_address: 172.0.0.82

  php81:
    restart: unless-stopped
    build:
      context: ./service/php81-fpm
    volumes:
      - ${WWW_ROOT:-../src}:/home/www
      - ${CONF_ROOT:-./conf}/php/8.1:/usr/local/etc/php
      - /opt/work/php:/opt/work/php
    networks:
      default:
        ipv4_address: 172.0.0.81

  php80:
    restart: unless-stopped
    build:
      context: ./service/php80-fpm
    volumes:
      - ${WWW_ROOT:-../src}:/home/www
      - ${CONF_ROOT:-./conf}/php/8.0:/usr/local/etc/php
      - /opt/work/php:/opt/work/php
    networks:
      default:
        ipv4_address: 172.0.0.80

  php74:
    restart: unless-stopped
    build:
      context: ./service/php74-fpm
    volumes:
      - ${WWW_ROOT:-../src}:/home/www
      - ${CONF_ROOT:-./conf}/php/7.4:/usr/local/etc/php
      - /opt/work/php:/opt/work/php
    networks:
      default:
        ipv4_address: 172.0.0.74

  php56:
    restart: unless-stopped
    build:
      context: service/php56-fpm
    volumes:
      - ${WWW_ROOT:-../src}:/home/www
      - ${CONF_ROOT:-./conf}/php/5.6:/usr/local/etc/php
      - /opt/work/php:/opt/work/php
    networks:
      default:
        ipv4_address: 172.0.0.56

  php54:
    restart: unless-stopped
    build:
      context: service/php54-fpm
    platform: linux/amd64
    volumes:
      - ${WWW_ROOT:-../src}:/home/www
      - ${CONF_ROOT:-./conf}/php/5.4:/usr/local/etc
      - /opt/work/php:/opt/work/php
    networks:
      default:
        ipv4_address: 172.0.0.54

  php53:
    restart: unless-stopped
    build:
      context: service/php53-fpm
    platform: linux/amd64
    volumes:
      - ${WWW_ROOT:-../src}:/home/www
      - ${CONF_ROOT:-./conf}/php/5.3:/usr/local/etc
      - /opt/work/php:/opt/work/php
    networks:
      default:
        ipv4_address: 172.0.0.53

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/24
